"""userservers

Revision ID: dca2717b4ba6
Revises: b3faf853662b
Create Date: 2023-11-22 15:08:14.907940

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dca2717b4ba6"
down_revision: str | None = "b3faf853662b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_servers",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["servers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "server_id"),
    )
    op.drop_constraint("fk_users_servers", "users", type_="foreignkey")
    op.drop_column("users", "server_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("server_id", sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key("fk_users_servers", "users", "servers", ["server_id"], ["id"])
    op.drop_table("user_servers")
    # ### end Alembic commands ###
